### ISSUE TITLE
luigi-td on Luigi 2.0  doesn't work

### ISSUE THREAD

**Issue by toru-takahashi** [treasure-data/luigi-td#1]
I try to the following installation. But, it show the followoing error.
http://luigi-td.readthedocs.org/en/latest/gettingstarted.html#installation

Do you know the cause?

```
$ python tasks.py MyQuery --local-scheduler
Traceback (most recent call last):
  File "tasks.py", line 4, in <module>
    import luigi_td
  File "/Users/takahashi/.pyenv/versions/2.7.9/lib/python2.7/site-packages/luigi_td/__init__.py", line 2, in <module>
    from luigi_td.task import *
  File "/Users/takahashi/.pyenv/versions/2.7.9/lib/python2.7/site-packages/luigi_td/task.py", line 32, in <module>
    class TableTask(luigi.Task):
  File "/Users/takahashi/.pyenv/versions/2.7.9/lib/python2.7/site-packages/luigi_td/task.py", line 37, in TableTask
    schema = luigi.Parameter(is_list=True, default=[], significant=False)
TypeError: __init__() got an unexpected keyword argument 'is_list'
```

```
$ pip list | grep luigi
luigi (2.0.0)
luigi-td (0.6.1)
```

**Comment by k24d** [comment]
Released 0.6.6.
